### ISSUE TITLE
Start mysql server on macOS

### ISSUE THREAD

**Issue by jiacai2050** [zigcc/zig-cookbook#54]
When working on #52, start mysql server always fails, so I disable run CI on macOS.

https://github.com/zigcc/zig-cookbook/actions/runs/8203449593/job/22436210107
```
/usr/local/opt/mysql@8.0/bin/mysql -e "CREATE USER '$USER'@'localhost' IDENTIFIED BY ''"
Warning: n: [Warning] Using a password on the command line interface can be insecure.
/usr/local/opt/mysql@8.0/bin/mysql -e "GRANT ALL PRIVILEGES ON *.* TO '$USER'@'localhost'"
mysqladmin: connect to server at 'localhost' failed
/usr/local/opt/mysql@8.0/bin/mysql -e "FLUSH PRIVILEGES"
error: 'Access denied for user 'root'@'localhost' (using password: YES)'
/usr/local/opt/mysql@8.0/bin/mysqladmin -proot password '123'
node:child_process:965
    throw err;
    ^

Error: Command failed: /usr/local/opt/mysql@8.0/bin/mysqladmin -proot password '123'
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at run (/Users/runner/work/zig-cookbook/zig-cookbook/.github/ci.js:14:3)
    at Object.<anonymous> (/Users/runner/work/zig-cookbook/zig-cookbook/.github/ci.js:40:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:[101](https://github.com/zigcc/zig-cookbook/actions/runs/8203449593/job/22436210107#step:6:102)3:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
  status: 1,
  signal: null,
```

**Comment by fwx5618177** [comment]
https://github.com/zigcc/zig-cookbook/pull/55/checks PTAL.
